social_portal/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.urls import path, include
from rest_framework import routers

from portal_app import views
from portal_app.views import LandingView, LoginView, LogoutView, UserProfileView, PhotoCreateView, \
    PostCreateView, ProfileEditView, CommentToPostAddView, GroupView, GroupDetail, GroupPostCreateView, GroupAppendView, \
    GroupCreateView, UsersGroupeView, CommentToPhotoAddView, MessagesView, MessagesWithUser, LikePostView, \
    UserRegistrationView, GroupeDelete, GroupeRequests, GroupeRequestsAcceptUser, GroupeRequestsRejectUser, GroupeLeave, \
    LikeView
from social_portal import settings
from django.contrib.auth import views as auth_views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'posts', views.PostViewSet)
router.register(r'groupe', views.GroupeViewSet)
router.register(r'categories', views.CategoryViewSet)
router.register(r'add_info', views.CategoryViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),  # test done
    path('', LandingView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),  # test done
    path('register/', UserRegistrationView.as_view(), name='register'),  # test done
    path('logout/', LogoutView.as_view(), name='logout'),  # test done
    path('profile/<str:username>', UserProfileView.as_view(), name='user-profile'),  # test done
    path('add_photo/', PhotoCreateView.as_view(), name='add-photo'),  # test omitted
    path('add_post/', PostCreateView.as_view(), name='add-post'),  # test done
    path('like-post/<int:post_id>/', LikePostView.as_view(), name='like-post'),  # test done
    path('profile/<str:username>/edit', ProfileEditView.as_view(), name='edit-user'),  # test done
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='commons/change-password.html',
            success_url='/'
        ),
        name='change_password'
    ),
    path('comment-post/<int:post_id>', CommentToPostAddView.as_view(), name='comment-post'),  # test done
    path('comment-photo/<int:photo_id>', CommentToPhotoAddView.as_view(), name='comment-photo'),  # test omitted
    # groups
    path('groups/', GroupView.as_view(), name='groups'),  # test done
    path('group/<slug:slug>/', GroupDetail.as_view(), name='group-details'),  # test done
    path('group/<slug:slug>/add_post/', GroupPostCreateView.as_view(), name='group-post'),  # test done
    path('group/<slug:slug>/append', GroupAppendView.as_view(), name='group-append'),  # test done
    path('create-group/', GroupCreateView.as_view(), name='create-group'),  # test done
    path('<str:username>/groups/', UsersGroupeView.as_view(), name='users-groups'),  # test done
    path('groups/delete/<slug:slug>/', GroupeDelete.as_view(), name='group-delete'),  # test done
    path('groups/requests-users/<slug:slug>/', GroupeRequests.as_view(), name='group-requests'),
    path('groups/requests-users/<slug:slug>/accept/<str:username>/', GroupeRequestsAcceptUser.as_view(),
         name='group-user-accept'),  # test done
    path('groups/requests-users/<slug:slug>/reject/<str:username>/', GroupeRequestsRejectUser.as_view(),
         name='group-user-reject'),  # test done
    path('groups/leave/<slug:slug>/', GroupeLeave.as_view(), name='group-leave'),  # test done

    # messages
    path('messages/', MessagesView.as_view(), name='messages'),  # test done
    path('messages/<str:with_username>', MessagesWithUser.as_view(), name='messages-with-user'),  # test done

    # API
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('like/', LikeView.as_view(), name='like'),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal_app/models.py
import datetime

from django.db import models
from django.conf import settings
from django.utils.text import slugify


class AdditionalInfo(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    motorcycle = models.CharField(max_length=64, default=None, null=True)
    date_of_birth = models.DateField(default=None, null=True)
    city = models.CharField(max_length=64, default=None, null=True)

    @property
    def age(self):
        return (datetime.datetime.now().date() - self.date_of_birth).days // 365


class Post(models.Model):
    content = models.TextField(verbose_name='Treść')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_add = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    groupe = models.ForeignKey('Groupe', on_delete=models.SET_DEFAULT, null=True, default=None)

    class Meta:
        ordering = ['-date_add']


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class Photo(models.Model):
    photo = models.ImageField(blank=True, verbose_name='Zdjęcie')
    description = models.CharField(max_length=255, null=True, default=None, verbose_name='Opis')
    date_add = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, default=None)
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE, null=True, default=None)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_add = models.DateTimeField(auto_now_add=True)


class Category(models.Model):
    name = models.CharField(max_length=64)
    upper_class_category = models.ForeignKey('self', on_delete=models.CASCADE, null=True, default=None)

    def __str__(self):
        return self.name


class Groupe(models.Model):
    name = models.CharField(max_length=128)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL)
    slug = models.SlugField(max_length=128, null=True, default=None, unique=True)
    moderators = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='moderating_groups')
    to_join = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='groups_to_join', blank=True)

    def get_categories_list(self):
        cat = self.category
        path = [cat.name]
        while cat.upper_class_category:
            path.append(cat.upper_class_category.name)
            cat = cat.upper_class_category
        path.reverse()
        path = '➝'.join(path)
        return path

    def save(self, *args, **kwargs):
        if self.slug is None:
            i = 1
            slug_start = slugify(self.name)
            slug = slug_start
            while True:
                try:
                    Groupe.objects.get(slug=slug)
                except:
                    break
                i += 1
                slug = slug_start + f'_{i}'
            self.slug = slug
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['category']


class Messages(models.Model):
    content = models.TextField()
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='from_msg')
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='to_msg')
    date = models.DateTimeField(auto_now_add=True)
    seen = models.BooleanField(default=False, null=False)

portal_app/views.py
from itertools import chain
from operator import attrgetter

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User, Group
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import FormView, CreateView, ListView, DetailView, DeleteView
from rest_framework import viewsets, permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView

from portal_app.forms import RegistrationForm, LoginForm, ImageForm, EditUserForm, MessageForm
from portal_app.models import Photo, Post, AdditionalInfo, Comment, Category, Groupe, Messages, Like
from django.contrib.auth import views as auth_views

from portal_app.serializers import LikeSerializer, UserSerializer, GroupSerializer, PostSerializer, GroupeSerializer, \
    CategorySerializer, AdditionalInfoSerializer


class LandingView(View):
    def get(self, request):
        return render(request, 'landing_page.html')


# class UserRegistrationView(View):
#     def get(self, request):
#         form = RegistrationForm()
#         return render(request, 'registration.html', {'form': form})
#
#     def post(self, request):
#         form = RegistrationForm(request.POST)
#         if form.is_valid():
#             if form.cleaned_data['password'] == form.cleaned_data['password2']:
#                 try:
#                     # validate_password(password=form.cleaned_data['password'])
#                     u = User.objects.create_user(username=form.cleaned_data['username'],
#                                                  password=form.cleaned_data['password'],
#                                                  first_name=form.cleaned_data['first_name'],
#                                                  last_name=form.cleaned_data['last_name'],
#                                                  email=form.cleaned_data['email'])
#                     AdditionalInfo.objects.create(
#                         user=u,
#                         motorcycle=form.cleaned_data['motorcycle'],
#                         date_of_birth=form.cleaned_data['date_of_birth'],
#                         city=form.cleaned_data['city']
#                     )
#
#                 except IntegrityError:
#                     return render(request, 'registration.html', {'form': form, 'error': 'Użytkownik już istnieje'})
#                 except ValidationError as e:
#                     return render(request, 'registration.html',
#                                   {'form': form, 'error': f'Hasło nie spełnia wymagań: {e}'})
#
#                 return redirect(reverse('home'))

class UserRegistrationView(FormView):
    form_class = RegistrationForm
    template_name = 'registration.html'

    def get_success_url(self):
        return reverse('home')


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(request, username=form.cleaned_data['username'],
                                password=form.cleaned_data['password'])
            if user:
                login(request, user)
                if request.GET.get('next'):
                    return redirect(request.GET.get('next'))
                return redirect(reverse('user-profile', kwargs={'username': user.username}))
            else:
                return render(request, 'login.html', {'form': form, 'error': 'Błędne dane logowania'})
        else:
            return HttpResponse('BŁĄD')


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(reverse('home'))


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request, username):
        user = User.objects.get(username=username)
        content_post = Post.objects.filter(user=user, group__isnull=True).order_by('-date_add')
        content_photo = Photo.objects.filter(user=user).order_by('-date_add')
        context = {
            'user_requested': user,
            'content_post': content_post,
            'content_photo': content_photo,
        }
        return render(request, 'userprofileview.html', context)


class LikePostView(View):
    def post(self, request, post_id):
        post = Post.objects.get(pk=post_id)
        post.likes += 1
        post.save()
        user = post.user
        return redirect(reverse('user-profile', kwargs={'username': user.username}))


# class PhotoCreateView(LoginRequiredMixin, CreateView):
#     model = Photo
#     fields = ['photo', 'description']
#     template_name = 'photo_create_form.html'
#
#     def form_valid(self, form):
#         user = self.request.user
#         form.instance.user = user
#         return super(PhotoCreateView,self).form_valid(form)
#
#     def get_success_url(self):
#         return reverse('user-profile', self.request.user.username)

class PhotoCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = ImageForm()
        return render(request, 'photo_create_form.html', {'form': form})

    def post(self, request):
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            newPhoto = Photo.objects.create(photo=request.FILES['photo'], user=request.user,
                                            description=form.cleaned_data['description'])
            return redirect(reverse('user-profile', kwargs={'username': request.user.username}))


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['content']
    template_name = 'post_create_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('user-profile', kwargs={'username': self.request.user.username})


class ProfileEditView(View):
    def get(self, request, username):
        user = User.objects.get(username=username)
        form = EditUserForm(initial={
            'username': username,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email,
            'motorcycle': user.additionalinfo.motorcycle,
            'date_of_birth': user.additionalinfo.date_of_birth,
            'city': user.additionalinfo.city
        })
        return render(request, 'editProfile.html', {'form': form})

    def post(self, request, username):
        form = EditUserForm(request.POST)
        user = User.objects.get(username=username)
        if form.is_valid():
            try:
                user = User.objects.get(username=username)
                user.username = form.cleaned_data['username']
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.email = form.cleaned_data['email']
                user.additionalinfo.motorcycle = form.cleaned_data['motorcycle']
                user.additionalinfo.date_of_birth = form.cleaned_data['date_of_birth']
                user.additionalinfo.city = form.cleaned_data['city']
                user.additionalinfo.save()
                user.save()
            except IntegrityError:
                return render(request, 'editProfile.html', {'form': form, 'error': 'Podany login jest zajęty'})
        return redirect(reverse('user-profile', kwargs={'username': user.username}))


class CommentToPostAddView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['content']
    template_name = 'portal_app/comment_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = get_object_or_404(Post, pk=self.kwargs.get('post_id'))
        return super().form_valid(form)

    def get_success_url(self):
        post = Post.objects.get(pk=self.kwargs.get('post_id'))
        return reverse('user-profile', kwargs={'username': post.user})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        commented_item = get_object_or_404(Post, pk=self.kwargs.get('post_id'))
        context["commented_item"] = commented_item
        return context


class CommentToPhotoAddView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['content']
    template_name = 'portal_app/commentPhoto_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.photo = get_object_or_404(Photo, pk=self.kwargs.get('photo_id'))
        return super().form_valid(form)

    def get_success_url(self):
        photo = Photo.objects.get(pk=self.kwargs.get('photo_id'))
        return reverse('user-profile', kwargs={'username': photo.user})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(self.kwargs.get('photo_id'))
        commented_item = get_object_or_404(Photo, pk=self.kwargs.get('photo_id'))

        context["commented_item"] = commented_item
        return context


###################GRUPY#########################

class GroupView(LoginRequiredMixin, ListView):
    model = Groupe
    paginate_by = 20


class GroupDetail(UserPassesTestMixin, LoginRequiredMixin, DetailView):
    def test_func(self):
        slug = self.kwargs.get("slug")
        groupe = Groupe.objects.get(slug=slug)
        user = self.request.user
        if groupe.users.filter(id=user.id).exists():
            return True
        else:
            return False

    model = Groupe

portal_app/templates/portal_app/commentPhoto_form.html
{% extends 'base.html' %}
{% block title %}Dodaj komentarz{% endblock %}
{% block content %}
    {#    <div>#}
    {#        <p class="commentContent">{{ commented_item.photo }}</p>#}
    {#        <p class="commentCreator">{{ commented_item.user.username }}</p>#}
    {#    </div>#}

    <div class="singlePhoto">
        <div class="photoContent">
            <img src="{{ commented_item.photo.url }}">
            <p class="photoDescription">{{ commented_item.description }}</p>
        </div>
        <div class="comments">
            {% for comm in commented_item.comment_set.all %}
                <p class="commentContent">{{ comm.content }}</p>
                <p class="commentCreator"><a class="commentCreator"
                                             href="{% url 'user-profile' comm.user.username %}">{{ comm.user.username }}</a>
                </p>
            {% endfor %}
        </div>
        <div class="datePost">{{ item.date_add|date:'d.m.Y H:i' }}</div>
    </div>


    <div class="error">{{ error }}</div>
    <form id="commentForm" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input id="login-btn" type="submit" VALUE="Dodaj">
    </form>
{% endblock %}

portal_app/templates/portal_app/comment_form.html
{% extends 'base.html' %}
{% block title %}Dodaj komentarz{% endblock %}
{% block content %}
    <div>
        <p class="commentContent">{{ commented_item.content }}</p>
        <p class="commentCreator">{{ commented_item.user.username }}</p>
    </div>
    <div class="error">{{ error }}</div>
    <form id="commentForm" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input id="login-btn" type="submit" VALUE="Dodaj">
    </form>
{% endblock %}

portal_app/templates/portal_app/group_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Grupy{% endblock %}
{% block content %}
    <div class="error">{{ error }}</div>
    <ul>
        {% for group in object_list %}
            <li class="singleGroup">
                <div class="groupName">
                    <a href="{% url 'group-details' group.slug %}">{{ group.name }}</a>
                    <button>Dołącz</button>
                </div>
                <div class="hide">
                    {% for list in group.get_categories_list %}
                        <p class="categoryPath">{{ list }}</p>
                    {% endfor %}
                </div>
            </li>
        {% endfor %}

    </ul>
    <script src={% static 'groupView.js' %}></script>
{% endblock %}

portal_app/templates/portal_app/groupe_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Usuwanie grupy {{ object.name }}{% endblock %}
{% block content %}
    <div class="error">{{ error }}</div>
    <form method="post">{% csrf_token %}
        <p>Czy napewno chcesz usunąć grupę "{{ object.name }}"?</p>
        <input class="inputAsButton" type="submit" value="Usuń">
    </form>
    <button onclick="location.href='{% url 'group-details' object.slug %}'">Nie</button>

{% endblock %}

portal_app/templates/portal_app/groupe_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ object.name }}{% endblock %}
{% block content %}
    <div class="error">{{ error }}</div>
    <div class="profileActions">
    {% if user in object.moderators.all %}

        <span class="editContentSpan">
            <button onclick="location.href='{% url 'group-delete' object.slug %}'">Usuń grupe</button>
        </span>

            <span class="editContentSpan">
            <button onclick="location.href='{% url 'group-requests' object.slug %}'">Przeglądaj prośby o dołączenie</button>
        </span>

            {#            <span class="addContentSpan">#}
            {#            <button onclick="location.href='/add_photo'">Dodaj zdjęcie</button>#}
            {#            <button onclick="location.href='/add_post'">Dodaj post</button>#}
            {#        </span>#}

    {% endif %}
    <button onclick="location.href='{% url 'group-leave' object.slug %}'">Opuść grupę</button>
    </div>
    <h2 class="pageTitle">Grupa {{ object.name }}</h2>
    <p>Liczba członków: {{ object.users.count }}</p>
    <div class="groupAction">
        <span class="addContentSpan">
            <button onclick="location.href='{% url 'group-post' object.slug %}'">Dodaj post</button>
        </span>
    </div>
    <div class="groupContent">
        <button id='hidePostsBtn' class="hide-btn">Ukryj posty</button>
        {% for item in object.post_set.all %}
            <div class="singlePost">
                <div class="postContent">
                    <div>{{ item.content }}</div>
                    <p class="commentCreator"><a class="commentCreator"
                                                 href="{% url 'user-profile' item.user.username %}">{{ item.user.username }}</a>
                    </p>
                </div>
                <div class="comments">
                    {% for comm in item.comment_set.all %}
                        <p class="commentContent">{{ comm.content }}</p>
                        <p class="commentCreator"><a class="commentCreator"
                                                     href="{% url 'user-profile' comm.user.username %}">{{ comm.user.username }}</a>
                        </p>
                    {% endfor %}
                    <button onclick="location.href='{% url 'comment-post' item.id %}'">Dodaj komentarz</button>
                </div>
                <div class="datePost">{{ item.date_add|date:'d.m.Y H:i' }}</div>
            </div>

        {% endfor %}

{% endblock %}

portal_app/templates/portal_app/groupe_form.html
{% extends 'base.html' %}
{% block title %}Utwórz grupę{% endblock %}
{% block content %}
    <form id="groupForm" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input id="login-btn" type="submit" VALUE="Utwórz">
    </form>
{% endblock %}

portal_app/templates/portal_app/groupe_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Grupy{% endblock %}
{% block content %}
    <div class="error">{{ error }}</div>
    <div class="groupActions">
        <button onclick="location.href='{% url 'create-group' %}'">Utwórz grupę</button>
    </div>
    <ul>
        {% for group in object_list %}
            <li class="singleGroup">
                <div class="groupName">
                    <a href="{% url 'group-details' group.slug %}">{{ group.name }}</a>
                    {% if group in request.user.groupe_set.all %}
                        <p>Jesteś członkiem tej grupy</p>
                    {% elif group in request.user.groups_to_join.all %}
                        <p>Oczekujesz na akceptację dołączenia do grupy przez jej moderatora</p>
                    {% else %}
                        <button onclick="location.href='{% url 'group-append' group.slug %}'">Dołącz</button>
                    {% endif %}
                </div>
                <div class="hide">
                    <p class="categoryPath">{{ group.get_categories_list }}</p>
                </div>
            </li>
        {% endfor %}

    </ul>
    <script src={% static 'groupView.js' %}></script>
{% endblock %}

portal_app/templates/portal_app/usersList_forMessages.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Wiadomości{% endblock %}
{% block content %}
    <div class="error">{{ error }}</div>
    <ul>
        {% for user in object_list %}
            {% if user != request.user %}
                <li class="singleUser">
                    <a href="{% url 'messages-with-user' user.username %}">{{ user.username }}</a>
                    {% if user.unseen > 0 %}
                        <span class="unseenMessages"> {{ user.unseen }} </span>
                    {% endif %}
                </li>
            {% endif %}
        {% endfor %}
    </ul>
    <script src={% static 'messages_list.js' %}></script>
{% endblock %}

portal_app/templates/portal_app/usersgroups_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Grupy{% endblock %}
{% block content %}
    <div class="error">{{ error }}</div>
    <div class="groupActions">
        <button onclick="location.href='{% url 'create-group' %}'">Utwórz grupę</button>
        <button onclick="location.href='{% url 'groups' %}'">Przeglądaj grupy</button>
    </div>
    <ul>
        {% for group in object_list %}
            <li class="singleGroup">
                <div class="groupName">

                    {% if group in request.user.groups_to_join.all %}
                        <span>{{ group.name }}</span>
                        <span>(Oczekujesz na akcpetację)</span>
                    {% else %}
                        <a href="{% url 'group-details' group.slug %}">
                            {{ group.name }}
                        </a>
                    {% endif %}
                </div>
                <div class="hide">
                    <p class="categoryPath">{{ group.get_categories_list }}</p>
                </div>
            </li>
        {% endfor %}

    </ul>
    <script src={% static 'groupView.js' %}></script>
{% endblock %}